apiVersion: v1
kind: Secret
metadata:
  name: {{ template "turtl.fullname" . }}
type: Opaque
data:
  dburl: {{- printf "postgres://%s:%s@%s:%s/%s" .Values.turtl.dbUsername .Values.turtl.dbPassword .Values.turtl.dbHost .Values.turtl.dbPort .Values.turtl.dbName | b64enc | quote -}}