apiVersion: v1
kind: Secret
metadata:
  name: {{ template "turtl.fullname" . }}
type: Opaque
data:
  dburl: postgres://{{ .Values.turtl.dbUsername }}:{{ .Values.turtl.dbPassword }}@{{ .Values.turtl.dbHost }}:{{ .Values.turtl.dbPort }}/{{ .Values.turtl.dbName }}
